---

- name: Configure Monitoring and Move Monitoring to Infra nodes
  kubernetes.core.k8s:
    api_version: v1
    state: present
    kind: ConfigMap
    name: cluster-monitoring-config
    namespace: openshift-monitoring
    merge_type:
      - strategic-merge
      - merge
    definition:
      data:
        config.yaml: |+
          enableUserWorkload: true
          alertmanagerMain:
            nodeSelector:
              node-role.kubernetes.io/infra: ""
            volumeClaimTemplate:
            spec:
              storageClassName: "{{ monitoring_storage_class }}"
              volumeMode: Filesystem
              resources:
                requests:
                  storage: 1Gi
          prometheusK8s:
            retention: 7d
            nodeSelector:
              node-role.kubernetes.io/infra: ""
            volumeClaimTemplate:
            spec:
              storageClassName: "{{ monitoring_storage_class }}"
              volumeMode: Filesystem
              resources:
                requests:
                  storage: 50Gi
          prometheusOperator:
            nodeSelector:
              node-role.kubernetes.io/infra: ""
          grafana:
            nodeSelector:
              node-role.kubernetes.io/infra: ""
          k8sPrometheusAdapter:
            nodeSelector:
              node-role.kubernetes.io/infra: ""
          kubeStateMetrics:
            nodeSelector:
              node-role.kubernetes.io/infra: ""
          telemeterClient:
            nodeSelector:
              node-role.kubernetes.io/infra: ""
          openshiftStateMetrics:
            nodeSelector:
              node-role.kubernetes.io/infra: ""

- name: Configure User Workload Monitoring
  kubernetes.core.k8s:
    api_version: v1
    state: present
    kind: ConfigMap
    name: user-workload-monitoring-config
    namespace: openshift-user-workload-monitoring
    merge_type:
      - strategic-merge
      - merge
    definition:
      data:
        config.yaml: |+
          prometheus:
            retention: 72h
            nodeSelector:
              node-role.kubernetes.io/infra: ""
            volumeClaimTemplate:
            spec:
              storageClassName: "{{ monitoring_storage_class }}"
              volumeMode: Filesystem
              resources:
                requests:
                  storage: 5Gi
          thanosRuler:
            nodeSelector:
              node-role.kubernetes.io/infra: ""